#############################################################################
# Makefile for building: main
# Generated by qmake (1.07a) (Qt 3.3.8b) on: Sun Jun 12 23:00:59 2016
# Project:  main.pro
# Template: app
# Command: $(QMAKE) -o Makefile main.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fno-strict-aliasing  -DQT_NO_DEBUG -DQT_SHARED -DQT_TABLET_SUPPORT -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -Wall -W -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fno-strict-aliasing -O3  -DQT_NO_DEBUG -DQT_SHARED -DQT_TABLET_SUPPORT -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/lib64/qt-3.3/mkspecs/default -I. -I/share/apps/6.0/boost/boost_1_51_0_gnu446_x86_64/include -I../../../earth/packages/tiff-4.0.3/include -I../../SMC_EM/cubature -I../../SMC_EM/emlib -I$(QTDIR)/include
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -L/share/apps/6.0/boost/boost_1_51_0_gnu446_x86_64/lib -lboost_system -lboost_filesystem -L/project/earth/packages/tiff-4.0.3/bin -L/project/earth/packages/tiff-4.0.3/lib -ltiff -lqt-mt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = obj/

####### Files

HEADERS = ../../SMC_EM/emlib/DataManager/DataManager.h \
		../../SMC_EM/emlib/EMManager/EMManager.h \
		../../SMC_EM/emlib/SMC/SMC.h \
		../../SMC_EM/emlib/FileManager/FileManager.h \
		../../SMC_EM/emlib/MotionModels/IMotionModel.h \
		../../SMC_EM/emlib/MotionModels/NoMotionModel.h \
		../../SMC_EM/emlib/MotionModels/DirectedDiffusionModel.h \
		../../SMC_EM/emlib/MotionModels/FreeDiffusionModel.h \
		../../SMC_EM/emlib/MotionModels/ConfinedDiffusionModel.h \
		../../SMC_EM/emlib/MotionModels/TetheredDiffusionModel.h \
		../../SMC_EM/emlib/InitialConditionModels/IInitialConditionModel.h \
		../../SMC_EM/emlib/InitialConditionModels/ConstantInitialCondition.h \
		../../SMC_EM/emlib/InitialConditionModels/NormalInitialCondition.h \
		../../SMC_EM/emlib/ObservationModels/IObservationModel.h \
		../../SMC_EM/emlib/ObservationModels/PoissonModel.h \
		../../SMC_EM/emlib/PointSpreadFunctions/GaussianPSF.h \
		../../SMC_EM/emlib/PointSpreadFunctions/PixelatedGaussianPSF.h \
		../../SMC_EM/emlib/Utilities/Utilities.cpp
SOURCES = main.cpp \
		../../SMC_EM/cubature/pcubature.c \
		../../SMC_EM/emlib/EMManager/EMManager.cpp \
		../../SMC_EM/emlib/SMC/SMC.cpp \
		../../SMC_EM/emlib/FileManager/FileManager.cpp \
		../../SMC_EM/emlib/MotionModels/NoMotionModel.cpp \
		../../SMC_EM/emlib/MotionModels/FreeDiffusionModel.cpp \
		../../SMC_EM/emlib/MotionModels/DirectedDiffusionModel.cpp \
		../../SMC_EM/emlib/MotionModels/ConfinedDiffusionModel.cpp \
		../../SMC_EM/emlib/MotionModels/TetheredDiffusionModel.cpp \
		../../SMC_EM/emlib/InitialConditionModels/ConstantInitialCondition.cpp \
		../../SMC_EM/emlib/InitialConditionModels/NormalInitialCondition.cpp \
		../../SMC_EM/emlib/ObservationModels/PoissonModel.cpp \
		../../SMC_EM/emlib/PointSpreadFunctions/GaussianPSF.cpp \
		../../SMC_EM/emlib/PointSpreadFunctions/PixelatedGaussianPSF.cpp \
		../../SMC_EM/emlib/Utilities/Utilities.cpp
OBJECTS = obj/main.o \
		obj/pcubature.o \
		obj/EMManager.o \
		obj/SMC.o \
		obj/FileManager.o \
		obj/NoMotionModel.o \
		obj/FreeDiffusionModel.o \
		obj/DirectedDiffusionModel.o \
		obj/ConfinedDiffusionModel.o \
		obj/TetheredDiffusionModel.o \
		obj/ConstantInitialCondition.o \
		obj/NormalInitialCondition.o \
		obj/PoissonModel.o \
		obj/GaussianPSF.o \
		obj/PixelatedGaussianPSF.o \
		obj/Utilities.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = 
OBJMOC = 
DIST	   = main.pro
QMAKE_TARGET = main
DESTDIR  = 
TARGET   = main

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: main.pro  /usr/lib64/qt-3.3/mkspecs/default/qmake.conf /usr/lib64/qt-3.3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile main.pro
qmake: 
	@$(QMAKE) -o Makefile main.pro

dist: 
	@mkdir -p obj/main && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) obj/main/ && ( cd `dirname obj/main` && $(TAR) main.tar main && $(GZIP) main.tar ) && $(MOVE) `dirname obj/main`/main.tar.gz . && $(DEL_FILE) -r obj/main

mocclean:

uiclean:

yaccclean:
lexclean:
clean:
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

obj/main.o: main.cpp ../../SMC_EM/emlib/DataManager/DataManager.h \
		../../SMC_EM/emlib/InitialConditionModels/NormalInitialCondition.h \
		../../SMC_EM/emlib/InitialConditionModels/ConstantInitialCondition.h \
		../../SMC_EM/emlib/MotionModels/FreeDiffusionModel.h \
		../../SMC_EM/emlib/MotionModels/DirectedDiffusionModel.h \
		../../SMC_EM/emlib/MotionModels/NoMotionModel.h \
		../../SMC_EM/emlib/ObservationModels/PoissonModel.h \
		../../SMC_EM/emlib/PointSpreadFunctions/GaussianPSF.h \
		../../SMC_EM/emlib/PointSpreadFunctions/PixelatedGaussianPSF.h \
		../../SMC_EM/emlib/SMC/SMC.h \
		../../SMC_EM/emlib/EMManager/EMManager.h \
		../../SMC_EM/emlib/FileManager/FileManager.h \
		../../SMC_EM/emlib/InitialConditionModels/IInitialConditionModel.h \
		../../SMC_EM/emlib/MotionModels/IMotionModel.h \
		../../SMC_EM/emlib/ObservationModels/IObservationModel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/pcubature.o: ../../SMC_EM/cubature/pcubature.c ../../SMC_EM/cubature/cubature.h \
		../../SMC_EM/cubature/clencurt.h \
		../../SMC_EM/cubature/converged.h \
		../../SMC_EM/cubature/vwrapper.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o obj/pcubature.o ../../SMC_EM/cubature/pcubature.c

obj/EMManager.o: ../../SMC_EM/emlib/EMManager/EMManager.cpp ../../SMC_EM/emlib/EMManager/EMManager.h \
		../../SMC_EM/emlib/SMC/SMC.h \
		../../SMC_EM/emlib/InitialConditionModels/IInitialConditionModel.h \
		../../SMC_EM/emlib/MotionModels/IMotionModel.h \
		../../SMC_EM/emlib/ObservationModels/IObservationModel.h \
		../../SMC_EM/emlib/FileManager/FileManager.h \
		../../SMC_EM/emlib/DataManager/DataManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/EMManager.o ../../SMC_EM/emlib/EMManager/EMManager.cpp

obj/SMC.o: ../../SMC_EM/emlib/SMC/SMC.cpp ../../SMC_EM/emlib/SMC/SMC.h \
		../../SMC_EM/emlib/InitialConditionModels/IInitialConditionModel.h \
		../../SMC_EM/emlib/MotionModels/IMotionModel.h \
		../../SMC_EM/emlib/ObservationModels/IObservationModel.h \
		../../SMC_EM/emlib/DataManager/DataManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/SMC.o ../../SMC_EM/emlib/SMC/SMC.cpp

obj/FileManager.o: ../../SMC_EM/emlib/FileManager/FileManager.cpp ../../SMC_EM/emlib/FileManager/FileManager.h \
		../../SMC_EM/emlib/DataManager/DataManager.h \
		../../SMC_EM/emlib/MotionModels/IMotionModel.h \
		../../SMC_EM/emlib/ObservationModels/IObservationModel.h \
		../../SMC_EM/emlib/InitialConditionModels/IInitialConditionModel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/FileManager.o ../../SMC_EM/emlib/FileManager/FileManager.cpp

obj/NoMotionModel.o: ../../SMC_EM/emlib/MotionModels/NoMotionModel.cpp ../../SMC_EM/emlib/MotionModels/NoMotionModel.h \
		../../SMC_EM/emlib/MotionModels/IMotionModel.h \
		../../SMC_EM/emlib/DataManager/DataManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/NoMotionModel.o ../../SMC_EM/emlib/MotionModels/NoMotionModel.cpp

obj/FreeDiffusionModel.o: ../../SMC_EM/emlib/MotionModels/FreeDiffusionModel.cpp ../../SMC_EM/emlib/MotionModels/FreeDiffusionModel.h \
		../../SMC_EM/emlib/MotionModels/IMotionModel.h \
		../../SMC_EM/emlib/DataManager/DataManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/FreeDiffusionModel.o ../../SMC_EM/emlib/MotionModels/FreeDiffusionModel.cpp

obj/DirectedDiffusionModel.o: ../../SMC_EM/emlib/MotionModels/DirectedDiffusionModel.cpp ../../SMC_EM/emlib/MotionModels/DirectedDiffusionModel.h \
		../../SMC_EM/emlib/MotionModels/IMotionModel.h \
		../../SMC_EM/emlib/DataManager/DataManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/DirectedDiffusionModel.o ../../SMC_EM/emlib/MotionModels/DirectedDiffusionModel.cpp

obj/ConfinedDiffusionModel.o: ../../SMC_EM/emlib/MotionModels/ConfinedDiffusionModel.cpp ../../SMC_EM/emlib/MotionModels/ConfinedDiffusionModel.h \
		../../SMC_EM/emlib/Utilities/Utilities.h \
		../../SMC_EM/emlib/MotionModels/IMotionModel.h \
		../../SMC_EM/emlib/DataManager/DataManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ConfinedDiffusionModel.o ../../SMC_EM/emlib/MotionModels/ConfinedDiffusionModel.cpp

obj/TetheredDiffusionModel.o: ../../SMC_EM/emlib/MotionModels/TetheredDiffusionModel.cpp ../../SMC_EM/emlib/MotionModels/TetheredDiffusionModel.h \
		../../SMC_EM/emlib/MotionModels/IMotionModel.h \
		../../SMC_EM/emlib/DataManager/DataManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/TetheredDiffusionModel.o ../../SMC_EM/emlib/MotionModels/TetheredDiffusionModel.cpp

obj/ConstantInitialCondition.o: ../../SMC_EM/emlib/InitialConditionModels/ConstantInitialCondition.cpp ../../SMC_EM/emlib/InitialConditionModels/ConstantInitialCondition.h \
		../../SMC_EM/emlib/InitialConditionModels/IInitialConditionModel.h \
		../../SMC_EM/emlib/DataManager/DataManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ConstantInitialCondition.o ../../SMC_EM/emlib/InitialConditionModels/ConstantInitialCondition.cpp

obj/NormalInitialCondition.o: ../../SMC_EM/emlib/InitialConditionModels/NormalInitialCondition.cpp ../../SMC_EM/emlib/InitialConditionModels/NormalInitialCondition.h \
		../../SMC_EM/emlib/InitialConditionModels/IInitialConditionModel.h \
		../../SMC_EM/emlib/DataManager/DataManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/NormalInitialCondition.o ../../SMC_EM/emlib/InitialConditionModels/NormalInitialCondition.cpp

obj/PoissonModel.o: ../../SMC_EM/emlib/ObservationModels/PoissonModel.cpp ../../SMC_EM/emlib/ObservationModels/PoissonModel.h \
		../../SMC_EM/emlib/ObservationModels/IObservationModel.h \
		../../SMC_EM/emlib/DataManager/DataManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/PoissonModel.o ../../SMC_EM/emlib/ObservationModels/PoissonModel.cpp

obj/GaussianPSF.o: ../../SMC_EM/emlib/PointSpreadFunctions/GaussianPSF.cpp ../../SMC_EM/emlib/PointSpreadFunctions/GaussianPSF.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/GaussianPSF.o ../../SMC_EM/emlib/PointSpreadFunctions/GaussianPSF.cpp

obj/PixelatedGaussianPSF.o: ../../SMC_EM/emlib/PointSpreadFunctions/PixelatedGaussianPSF.cpp ../../SMC_EM/emlib/PointSpreadFunctions/PixelatedGaussianPSF.h \
		../../SMC_EM/cubature/cubature.h \
		../../SMC_EM/emlib/PointSpreadFunctions/GaussianPSF.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/PixelatedGaussianPSF.o ../../SMC_EM/emlib/PointSpreadFunctions/PixelatedGaussianPSF.cpp

obj/Utilities.o: ../../SMC_EM/emlib/Utilities/Utilities.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Utilities.o ../../SMC_EM/emlib/Utilities/Utilities.cpp

####### Install

install:  

uninstall:  

